ktor:
  application:
    modules:
      - de.pigeonport.componentwarehouse.ApplicationKt.module
  deployment:
    port: 8080

db:
  mongo:
    user: root
    password: example
    host: pigeonport.de
    port: 8999
    database: component-warehouse